apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
  labels:
    app: probes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-demo
  template:
    metadata:
      labels:
        app: probes-demo
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh"]
        args: 
          - "-c"
          - 'sleep 10 && touch /tmp/flag.startup.complete && tail -f /dev/null'
        startupProbe:
          exec:
            command: 
            - cat
            - /tmp/flag.startup.complete
          failureThreshold: 9
          periodSeconds: 1
---
